### ISSUE TITLE
Transliteratation

### ISSUE THREAD

**Issue by vasnt** [Vaibhavs10/translate-with-whisper#3]
would be helpful for language learners, if transliteration is also available.
Reference:

- https://github.com/KSubedi/transliteration-input-tools
- https://www.google.co.in/inputtools/try/

**Comment by Vaibhavs10** [comment]
Hi @vasnt - Thanks for the URLs. Could you expand the intended behaviour you are looking for here? I can't seem to make a connection between whisper and transliteration instantly, unfortunately.

**Comment by vasnt** [comment]
@Vaibhavs10 

https://www.google.com/inputtools/services/features/transliteration.html

i also forgot it what i wanted to do. but can you look into this small video about transliteration. In case if you can find some use case for language learners by incorporating such feature.
